name: Disasters
version: '1.4.2'
main: me.hhitt.disasters.Disasters
api-version: '1.20'
authors: [ hhitt, erneto13 ]
description: "Fork del plugin Disasters, con eventos personalizado y únicos para el servidor GalaxyCraft. Desarrollado por erneto13. <3"
softdepend: [ Multiverse-Core ]
libraries:
- com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.21.0
- com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.21.0
